export enum FOOD_ACTIONS {
    FOOD_PRODUCTS_FETCHED = 'FOOD_PRODUCTS_FETCHED',
    FOOD_SEARCH_TEXT_CHANGED = 'FOOD_SEARCH_TEXT_CHANGED',
    RATING_CHANGED = 'RATING_CHANGED'
}

export enum CART_ACTION {
    ITEM_MODIFIED = 'ITEM_MODIFIED'
}
